apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: engineering
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: "amigoscode/kubernetes:customer-v1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ORDER_SERVICE
          value: "order"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: customer-node
  namespace: engineering
spec:
  type: NodePort
  selector:
    app: customer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: engineering
spec:
  type: ClusterIP
  selector:
    app: customer
  ports:
  - port: 80
    targetPort: 8080
