apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath
spec:
  selector:
    matchLabels:
      app: hostpath
  template:
    metadata:
      labels:
        app: hostpath
    spec:
      volumes:
      - name: var-log
        hostPath:
          path: /var/log
      containers:
      - name: hostpath
        volumeMounts:
          - mountPath: /var/log
            name: var-log
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "sleep"
          - "3600"
