apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: "amigoscode/kubernetes:order-v1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---

apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: ClusterIP
  selector:
    app: order # Должен совпадать с labels Deployment'а
  ports:
  - port: 8081 # Порт самого сервиса. Не обязательно, чтобы совпадал с портом Deployment'а
    targetPort: 8081 # Должен совпадать с портом Deployment'а
